# Generated by Django 3.0.2 on 2020-01-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookLibrary', '0002_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
